### ISSUE TITLE
Give @floogulinc credit for the Angular Material work

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab4_mongo-pre-S20#116]
@floogulinc did much of the initial transition to Angular Material in F17, but that's not always visible in the commit history because various people (faculty and TA's) copied code from one repo into another instead of trying to figure out how to move whole commits (with credit, etc.) from one repo to another.

Going back and "fixing" the commit history is essentially impossible, but it would be good to give @floogulinc some kind of credit for their valuable contributions.

Some options, which are not exclusive:

* Credit comments in the code
   * This one is a bit awkward because it's not entirely obvious which files to give him credit in/for. Putting credit in every file touched in that would put it in an awful lot of places, but maybe that's just the honest thing?
* Credit in the `README.md` file
* Create a `CREDITS.md` file and add him there
   * We've done this in a few other places (e.g., CSci 3403 labs) where some of the work pre-dates our use of `git`.

This also impacts [Lab 3](https://github.com/UMM-CSci-3601/3601-lab3_angular-spark) and [the production template](https://github.com/UMM-CSci-3601/production-template).

Thoughts?

**Comment by kklamberty** [comment]
I think the best approach is to do one of the options in README.md or CREDITS.md, but we might ask him for input on his preference.

**Comment by kklamberty** [comment]
When I asked him in the fall he said he didn't care since it was going to change a lot anyway. Now that is true and his commits will serve as credit. So, I'm closing this.
