### ISSUE TITLE
Update LABTASKS.md

### ISSUE THREAD

**Issue by carav008** [UMM-CSci-3601/3601-lab4_mongo-pre-S20#12]
We need to update the labtasks to reflect usage of Material Design this includes instructions as well as resources, etc

**Comment by kklamberty** [comment]
We need to update the LABTASKS.md to be sure we are clear on how we want them to answer the questions and where... if it goes in ANSWERS.md or a Google Doc or whatever... and what they should actually turn in should be clear on the rubric as well
