### ISSUE TITLE
Refactor E2E test

### ISSUE THREAD

**Issue by carav008** [UMM-CSci-3601/3601-lab4_mongo-pre-S20#13]
Refactor to fit new material design elements. Add test about _addUser()_ functionality

**Comment by kklamberty** [comment]
The E2E testing uses page objects in what appears to be a slightly non-standard manner. We may want to look into that a bit more and move some of the stuff around.

**Comment by kklamberty** [comment]
The page object file is meant to be used to define where certain elements are and how they are accessed, so the test file itself won't include those parts that are about accessing. We have not done this separation, and I think it would be helpful if we look at that and try to separate them a bit more. It helps make the tests clearer and less dependent on where things are located.

**Comment by NicMcPhee** [comment]
Nice – that makes a lot of sense. Separating concerns is almost always a Good Thing.
