### ISSUE TITLE
Migrate request, response functions to separate class

### ISSUE THREAD

**Issue by carav008** [UMM-CSci-3601/3601-lab4_mongo-pre-S20#14]
- Will now consist of a UserController class and and UserResponseHandler
- testing is now better in terms of coverage

**Comment by kklamberty** [comment]
This looks like it is fixed by commit 344acc186a11d5057a0aba2741569b47b012852e and several other commits on the improving-test-coverage branch. These are separated now (there are two classes) and there have been successful builds.
