### ISSUE TITLE
Change indentation from 4 spaces to 2 spaces

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab4_mongo-pre-S20#20]
To be consistent with previous labs we should change the indentation from 4 spaces to 2 spaces in `.editorconfig`, and then use IDEA to update the spacing on all our files.

**Comment by NicMcPhee** [comment]
Don't think this is going to happen in time for lab this semester. We should look at rationalizing our spacing across all the labs for next year.

**Comment by kklamberty** [comment]
Weird. It looks like this was done in this commit: commit c88cfa1e27581f19e612ccbb87356f8e9f3e024d 

Maybe it just wasn't update using IDEA yet.
