### ISSUE TITLE
Handle exiting out of add user dialogue gracefully

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab4_mongo-pre-S20#24]
Currently if you click "Exit" on the add user dialogue without entering anything, that throws an exception on the server side because we still try to add a new user with empty values for all the fields.

We should write tests that catch this, and then make sure it doesn't happen anymore.

**Comment by kklamberty** [comment]
We worked on this and fixed it, stashing the changes on KK's account. We will want to go back to this and do it properly with a branch and a test to capture the problem that we fixed.
