### ISSUE TITLE
We should test our error handling when adding a new user

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab4_mongo-pre-S20#27]
If we click "Exit" on the dialogue for adding a new user, it actually throws an exception on the _server_ because our front-end still sends an add request with essentially an "empty" user object. The front end shouldn't ever send the request, and we should test that.

**Comment by kklamberty** [comment]
I think this was addressed in [commit 80134b75ff12cdf0f81c082a26658646fcf29384](https://github.com/UMM-CSci-3601/3601-lab4_mongo/pull/31)
