### ISSUE TITLE
We should validate some input data when adding a user

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab4_mongo-pre-S20#28]
At the moment, you can enter pretty much any random text for the age, and we don't really validate that information in a sensible way, either on the front end or the back end. We should add tests and validation that makes sure users can't do "bad" things there. This is an important example for the students, who may need to do validation on input data in their todo work for the lab.

A simple solution would be to check for negative ages as those aren't prevented in any way at the moment.

**Comment by kklamberty** [comment]
Whoever adds this might also add E2E test(s) to verify this behaves as intended

**Comment by kklamberty** [comment]
We may also want to check for really long text so that students will see that Nic can't totally mess up their system with random novels.

**Comment by kklamberty** [comment]
I'm working on this and found a potentially useful course of information and examples: [sitepoint source: angular stuff including forms and tables](https://www.sitepoint.com/angular-material-design-components/) and [sitepoint source: specifically about forms](https://www.sitepoint.com/angular-forms/). Also, there is some information that might have led us to not have the weird errors about trying to make a new user if we'd done validation all along... [disable the submit button until the form's contents are valid](https://www.codelord.net/2015/11/06/angular-forms-and-validation-step-by-step-example/) -- note: the last link is not very recent, but some of the ideas from it may still work.

**Comment by NicMcPhee** [comment]
> We may also want to check for really long text so that students will see that Nic can't totally mess up their system with random novels.

This probably needs to include an E2E test because there are various places all through the system where really long inputs could break things.

And I really like that idea of disabling the submit button until the form's contents are valid – that's a totally excellent way to deal with that. Then all we'd have to worry about is handling cancel correctly.

**Comment by kklamberty** [comment]
Good plan. That should definitely be one or several of the E2E tests.
