### ISSUE TITLE
Change ngFor in UserListComponent so that it is no longer binded directly to the filter function

### ISSUE THREAD

**Issue by bushw011** [UMM-CSci-3601/3601-lab4_mongo-pre-S20#29]
Due to the way change detection works in Angular, if we generate our list with something like *ngFor="let user of filterUsers(param)", that filter function will be repeatedly called whenever any change whatsoever in the DOM is detected. This goes for clicking anything, scrolling (I think), or typing anything, even if our action has nothing to do with filtering, that function will be called over and over again hundreds of times. Filtering is an expensive operation, so this can be very problematic and is likely to blame for poor performance when transferring it over to the TodoListComponent, where there are hundreds of objects being dealt with. I'm assuming this is why the accordions and other things were so slow for the majority of the TodoLists this past lab.

What we want to be doing is to have the ngFor binded to just the filteredUsers array, and have the filter function only be called when things we care about change.

**Comment by kklamberty** [comment]
There seems to be some possibly useful information about filtering and data sources in the table documentation here: [material angular table](https://material.angular.io/components/table/overview) in the filtering section.

**Comment by kklamberty** [comment]
We have discussed this and determined that switching this to tables would be a good approach to try to handle it. We might be able to get some server side filtering by using pagination, but we will want to look at that. we will start by putting in tables and then go from there.

**Comment by kklamberty** [comment]
We will need to pull this change from lab 3 into lab 4.
