### ISSUE TITLE
Migrate to JUnit 5

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab4_mongo-pre-S20#32]
We're still using JUnit 4 everywhere, and we should at some point migrate to [JUnit 5](https://junit.org/junit5/docs/current/user-guide/) which has been out for over a year now and appears to have a number of cool features that might be useful or instructive. 

Not a huge priority, though, especially if no one has any particular ideas/plans for using the new JUnit 5 features.

**Comment by floogulinc** [comment]
Archiving this repo.
