### ISSUE TITLE
Can we get rid of the "has incorrect peer dependency" warnings?

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab4_mongo-pre-S20#37]
When we build the client side of the project we still get a bunch of `has incorrect peer dependency` warnings. It would be nice if we could try to figure out why those are happening and make them go away. Not a super high priority, but I do know that these warnings confuse students, and add clutter which makes it harder to see when something actually important gets printed out when we build things.

**Comment by kklamberty** [comment]
These are gone in lab 3 and should be fine if we use lab 3 as a basis for lab 4
