### ISSUE TITLE
We should get rid of specific beta version dependencies

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab4_mongo-pre-S20#39]
If you go look at [our JS dependencies](https://github.com/UMM-CSci-3601/3601-lab4_mongo/network/dependencies) there are a several hard coded versions that are tied to (now quite old) beta versions of libraries. This isn't great, and we should try to modify those to point to (for starters) the oldest non-beta version _after_ the version we currently point to.

The ones that show up in the dependency graph include:

- [x] `@angular/cdk`
- [ ] `@angular/flex-layout`
- [x] `@angular/material`
- [x] `covalent/core` (do we even still use `covalent`?)

Someone should looking into how hard/easy this is. If it's easy just fix all of them in one fell swoop. If it's hard we might want to split this into 4 different issues.

**Comment by nickplucker** [comment]
`@angular/cdk` and `@angular/material` will be upgraded once I merge in @NicMcPhee `upgrade-to-angular5` branch. `@angular/flex-layout` has always been in beta and `covalent/core` will be removed from the project.

**Comment by kklamberty** [comment]
These have been updated, but that definitely does not mean that they would not need updating again.
