### ISSUE TITLE
Upgrade to Gradle v5

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab4_mongo-pre-S20#45]
The current version of Gradle is 5.0.0 and we're using 3.1 in the labs.

I have no idea how easy/hard this will be and how it might affect things. At a minimum, I suspect it will make on-line documentation more useful. I tried changing testCompile to testImplementation to match this quick start guide and it didn't work, presumably because our Gradle is so old.

**Comment by NicMcPhee** [comment]
Turns out that you can upgrade Gradle wrappers "in place" trivially, so this should be really easy. Thanks to [this comment](https://github.com/UMM-CSci-3601/intro-to-git/issues/29#issuecomment-448053685) from @floogulinc for reminding me how easy that is. The details are at https://gradle.org/install/#with-the-gradle-wrapper

**Comment by kklamberty** [comment]
We need to stick to 4.10.3 I think it was (as we discovered in lab 0 on day one of class spring 2019) due to our older version of IntelliJ IDEA.

**Comment by kklamberty** [comment]
Does this mean this issue should be closed?

**Comment by floogulinc** [comment]
We should be running the latest InteliJ in the lab now because we are using the Snap so it should support modern stuff.

**Comment by kklamberty** [comment]
So, if IntelliJ supports it and it can be upgraded "in place"... does that mean it has been done and is handled or that we still need to actually do something?

**Comment by floogulinc** [comment]
Archiving this repo.
