### ISSUE TITLE
Replace anonymous `functions` with arrows (`=>`)

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab4_mongo-pre-S20#82]
In #81 @kklamberty and I decided that we wanted to update the code to match Google's JavaScript guidelines on anonymous functions, where they recommend using arrows (=>) instead of the function keyword. So instead of:

```TypeScript
page.getUsers().then(function (users) {
            expect(users.length).toBe(2);
});
```

we'd use

```TypeScript
page.getUsers().then((users) => {
            expect(users.length).toBe(2);
});
```

There are a lot of instances of anonymous functions with the function keyword, so switching to match this guideline might be a fair bit of work, but @kklamberty volunteered to take it on 'cause she's awesome!

**Comment by kklamberty** [comment]
[Documentation about arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) seems to indicate that they are not supported by Internet Explorer. It is also the case that we can't refer to arguments inside an anonymous arrow function, so some places we won't be able to change for now. That's fine, though.
