### ISSUE TITLE
Add NVM support

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab4_mongo-pre-S20#90]
Some of our dependencies can't update because we have a really old version of `node` installed. (We have version 6.12.0 and the current stable is 11.9.0.) Updating the global version in the lab is difficult for various reasons, so an alternative is to show them how to install and use `nvm` to download their own version of `node` and use that in the project.

Tasks:

* [ ] Update version of `node` specified in `.travis.yml` and make sure Travis builds with a newer version of node.
* [ ] Confirm that we can successfully accept various Dependabot pull requests after updating `node`.
   * If we can't, there's really no point.
* [ ] Add info to the write-up (maybe for Lab 3?) for installing `nvm` and using it to install and use the latest stable version.
   * I had some weirdness where my `.bash_profile` wasn't being read when I just opened a new terminal window. I'm not sure what will happen for students, but they may need to `source .bash_profile` when they first do all this.
   * We need to make it clear that all this should be a one-time thing and they shouldn't ever need to do it again. They may wish to use `nvm` in the future, though, to update/change/manage which version of `node` they're using.

**Comment by kklamberty** [comment]
This is no longer an issue in our lab.
